name = "quote-system-api"
main = "src/worker.js"
compatibility_date = "2025-05-01"

[vars]
ALLOWED_ORIGINS = "https://quote-system-frontend.pages.dev,https://pansanrequest.ccwu.cc,https://api.pansanrequest.ccwu.cc"
MAX_IMAGES = "5"
ADMIN_EMAIL = "zp1364625224@163.com"
FROM_EMAIL = "noreply@pansanrequest.ccwu.cc"

[[d1_databases]]
binding = "DB"
database_name = "quote-system"
database_id = "5584962d-60c1-431d-8151-3d2870a2784d"

[[r2_buckets]]
binding = "QUOTE_IMAGES"
bucket_name = "pansan-request-images"

[triggers]
crons = ["0 0 1 */6 *", "*/5 * * * *"]
