name = "quote-system-api"
main = "src/worker.js"
compatibility_date = "2026-05-07"

[vars]
ALLOWED_ORIGINS = "*"
MAX_IMAGES = "5"

[[d1_databases]]
binding = "DB"
database_name = "quote-system"
database_id = "5584962d-60c1-431d-8151-3d2870a2784d"

[[r2_buckets]]
binding = "QUOTE_IMAGES"
bucket_name = "pansan-request-images"

[triggers]
crons = ["0 0 1 */6 *"]

